### PR TITLE
add concept of user

### PR DESCRIPTION
**Pull request by omikuji**
@hannesdejager thank you last week!

I have organized [this pull request!
](https://github.com/bolcom/libunftp/pull/13)

thank you!

### CODE REVIEW

**Comment by hannesdejager** [comment]
For clarity, @omikuji 's commit overview from the previous MR: 

> added U for the purpose of giving user information to each action. By implementing this, you can change the behavior for each user. (For example, change the upload path prefix for each user.)

**Comment by hannesdejager** [comment]
A nice all the builds pass now.

**Comment by omikuji** [comment]
I'm so happy!!

**Comment by agoston** [comment]
@omikuji i have to partially revert your changes around making authenticator 'static. it probably wasn't clear, but we need the server configurable. I'm adding that in the unftp project now, but that also means that these fields have to be more dynamic than that.

We are planning to add a contribution guide so make this more clear.

**Comment by omikuji** [comment]
@agoston okay. thank you for the explanation.

**Pull request merged**
