### PR TITLE
Upgraded to tokio 1.0, bytes 1.0, hyper 0.14 and others

### PR DESCRIPTION
**Pull request by hannesdejager**

### CODE REVIEW

**Review by robklg — APPROVED** [review]

**Comment by OrangeTux** [comment]
Just came here to say thanks for upgrading to Tokio 1.0! Great job.

**Comment by hannesdejager** [comment]
@OrangeTux, the pleasure is ours! Thanks! Feel free to share with us your usecase. Always great to hear how people are using our system.

**Comment by OrangeTux** [comment]
We, at @mobilityhouse, use this project to update our fleet of charging stations for electric vehicles. Most of our stack is in Python, so we looked for Python implementations of an FTP server first. For various reasons those solutions didn't fit.
Than we discovered this project and implemented or own, small FTP server. It's supports only a few commands, but that is good enough for us. We wrote a Python wrapper for it using [pyo3](https://github.com/PyO3/PyO3/) and integrated the project into our Python application.

**Comment by hannesdejager** [comment]
Great to hear!!

[v0.15.0 release on crates.io](https://crates.io/crates/libunftp)

**Pull request merged**
