### PR TITLE
Fix building the examples on FreeBSD

### PR DESCRIPTION
**Pull request by asomers**

### CODE REVIEW

**Comment by asomers** [comment]
I assume that @hannesdejager disabled the capsicum-net dev dependency in order to publish release v0.2.5 . But good news!  As of today I've finally resolved the collaboration problem with the capsicum developer.  So I expect to publish a stable release of both capsicum and capsicum-net next week.

**Comment by asomers** [comment]
I do not know why cargo can fetch the git dependency on Windows and Linux but not OSX.

**Comment by hannesdejager** [comment]
> I assume that @hannesdejager disabled the capsicum-net dev dependency in order to publish release v0.2.5

Indeed sorry about that.  Let me know if the  stable release of both capsicum and capsicum-net are out.

**Comment by asomers** [comment]
@hannesdejager here you go!

**Pull request merged**
